services:
  stacktastic-main:
    image: stacktastic-main:${IMAGE_TAG}
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"

      # Primary domain router
      - "traefik.http.routers.stacktastic-main.rule=Host(`stacktastic.dev`)"
      - "traefik.http.routers.stacktastic-main.entrypoints=websecure"
      - "traefik.http.routers.stacktastic-main.tls.certresolver=myresolver"

      # Secondary www router
      - "traefik.http.routers.stacktastic-www.rule=Host(`www.stacktastic.dev`)"
      - "traefik.http.routers.stacktastic-www.entrypoints=websecure"
      - "traefik.http.routers.stacktastic-www.tls.certresolver=myresolver"

      # Shared service for both
      - "traefik.http.services.stacktastic-main.loadbalancer.server.port=3000"
    networks:
      - web

networks:
  web:
    external: true
