version: '3.9'

services:
  stacktastic-main:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.stacktastic-staging.rule=Host(`staging.stacktastic.dev`)'
      - 'traefik.http.routers.stacktastic-staging.entrypoints=web'
      - 'traefik.http.services.stacktastic-staging.loadbalancer.server.port=3000'
