export { default as Svelte } from './Svelte.svelte';
export { default as TypeScript } from './TypeScript.svelte';
export { default as GraphQL } from './GraphQL.svelte';
export { default as PostgreSQL } from './PostgreSQL.svelte';
export { default as TailwindCSS } from './TailwindCSS.svelte';
export { default as NodeJS } from './NodeJS.svelte';
export { default as Docker } from './Docker.svelte';
export { default as GitHub } from './GitHub.svelte';
export { default as SimpleIcon } from './SimpleIcon.svelte';
