name: Deploy stacktastic

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: stacktastic-main:${{ github.ref_name }}-${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build --pull -t $DOCKER_IMAGE .
          docker save $DOCKER_IMAGE | gzip > image.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "image.tar.gz"
          target: "~/stacktastic/${{ github.ref_name }}/"

      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.${{ github.ref_name }}.yml"
          target: "~/stacktastic/${{ github.ref_name }}/"

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd ~/stacktastic/${{ github.ref_name }}
            gunzip -f image.tar.gz
            docker load < image.tar
            docker-compose -f docker-compose.${{ github.ref_name }}.yml up -d
            rm -f image.tar
