name: Deploy stacktastic

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build --pull -t stacktastic-${{ github.ref_name }}:${{ github.sha }} .
          docker save stacktastic-${{ github.ref_name }}:${{ github.sha }} | gzip > image.tar.gz

      - name: Copy image and docker-compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "image.tar.gz,docker-compose.${{ github.ref_name }}.yml"
          target: "~/stacktastic/${{ github.ref_name }}/"

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd ~/stacktastic/${{ github.ref_name }}
            gunzip -f image.tar.gz
            docker load < image.tar
            IMAGE_TAG=${{ github.sha }} docker-compose -f docker-compose.${{ github.ref_name }}.yml up -d --force-recreate
            rm -f image.tar
